name: Reusable Deploy Workflow

on:
  workflow_call: 
    inputs:
      environment:
        required: true
        type: string
    secrets:
      DEPLOY_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to ${{ inputs.environment }}
        run: echo "Deploying with token ${{ secrets.DEPLOY_TOKEN }}"
