name: Demo Workflow

on:
  push:
    branches:
      - main

jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show Trigger Type
        run: |
          echo "This workflow was triggered by: ${{ github.event_name }}"
